import Head from "next/head";
import { FC } from "react";
import { IAdminLayout } from "@/types";
import { MainWrapper } from "./AdminLatout.styled";
import Header from "./Header";
import SideBar from "./SideBar";
import { Section } from "../CommonFormStyles";

const AdminLayout: FC<IAdminLayout> = ({ children, title }) => {
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <MainWrapper>
        <SideBar />
        <main>
          <Section>{children}</Section>
        </main>
      </MainWrapper>
    </>
  );
};

export default AdminLayout;
