import Head from "next/head";
import { Inter } from "next/font/google";
import Header from "@/components/Header";
import Slider from "@/components/Slider";
import About from "@/components/About";
import PartnersGallery from "@/components/PartnersGallery";
import Donate from "@/components/Donate";
import Footer from "@/components/Footer";

import FileOpenLink from "@/components/FileOpenLink";

import CookieConsentBanner from "@/components/CookieConsentBanner/CookieConsentBanner";


const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <main>
        <Slider />
        <About />
        <PartnersGallery />
        <Donate />
        <FileOpenLink path="/M8 FAQ_Russian.pdf" text="text" />
      </main>
      <Footer />
      <CookieConsentBanner />
    </>
  );
}
