import Head from "next/head";
import type { NextPage } from "next";
import Link from "next/link";

import { deleteSlide, getSlider } from "@/services";

const Slider: NextPage = () => {
  //test

  const getSlides = async () => {
    try {
      const response: any = await getSlider();
      console.log(response);
    } catch (error) {
      console.log(error);
    }
  };

  const deleteOneSlide = async (id: string) => {
    try {
      const response = await deleteSlide(id);
      console.log(response);
    } catch (e) {
      console.log(e);
    }
  };
  //test
  return (
    <>
      <Head>
        <title>Slider</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        Slider page
        <hr />
        <p style={{ color: "red" }}>Отримати слайди</p>
        <button onClick={getSlides}>Get slides</button>
        <button
          style={{ backgroundColor: "red", color: "white", marginLeft: "30px" }}
          onClick={() => deleteOneSlide("")}
        >
          Delete slide
        </button>
        <hr />
        <hr />
        <Link
          href={"/admin/slider/form"}
          style={{
            color: "blue",
            textDecoration: "underline",
            display: "block",
          }}
        >
          Add slide
        </Link>
      </main>
    </>
  );
};

export default Slider;
