import Head from "next/head";
import type { NextPage } from "next";
import Link from "next/link";

const Slider: NextPage = () => {
  return (
    <>
      <Head>
        <title>Slider</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        Slider page
        <Link href={"/admin/slider/form"}>Add slide</Link>
      </main>
    </>
  );
};

export default Slider;
