import Head from "next/head";
import type { NextPage } from "next";

const Form: NextPage = () => {
  return (
    <>
      <Head>
        <title>Partners Form</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>Partners Form Page</main>
    </>
  );
};

export default Form;
