import Head from "next/head";
import type { NextPage } from "next";
import Link from "next/link";

const Cards: NextPage = () => {
  return (
    <>
      <Head>
        <title>Partners</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        Partners page
        <Link href={"/admin/partners/form"}>Add partner</Link>
      </main>
    </>
  );
};

export default Cards;
