import { useRouter } from "next/router";
import { useSession, signOut } from "next-auth/react";
import { useEffect } from "react";
import Head from "next/head";
import type { NextPage } from "next";
import CardForm from "@/components/AdminPanel/CardForm/CardForm";
import ReportForm from "@/components/AdminPanel/ReportForm/ReportForm";
import ContactForm from "@/components/AdminPanel/ContactForm/ContactForm";
import PartnerForm from "@/components/AdminPanel/PartnerForm/PartnerForm";
import SliderForm from "@/components/AdminPanel/SliderForm/SliderForm";

const Admin: NextPage = () => {
  const { data: session } = useSession();

  const router = useRouter();

  const handleSignOut = async () => {
    await signOut({ callbackUrl: "/login" });
  };

  // useEffect(() => {
  //   if (session) {
  //     if (!session) {
  //       router.push("/login");
  //     }
  //   } else if (session === null) {
  //     router.push("/login");
  //   }
  // }, [session, router]); //теоретично роутер треба додавати в залежності, але і без нього все ніби працює

  return (
    <>
      {/* {session && ( */}
      <>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main>
          <h1>Сторінка адміну</h1>
          <>
            Signed in as {session?.user?.name} <br />
            <button onClick={handleSignOut}>Sign out</button>
          </>
          <br />
          <h2>Картка</h2>
          <br />
          <CardForm />
          <br />
          <h2>Звітність</h2>
          <br />
          <ReportForm />
          <br />
          <h2>Контакти</h2>
          <br />
          <ContactForm />
          <br />
          <h2>Партнери</h2>
          <br />
          <PartnerForm />
          <br />
          <h2>Слайдер</h2>
          <br />
          <SliderForm />
        </main>
      </>
      {/* )} */}
    </>
  );
};

export default Admin;
