import Head from 'next/head'
import LoginForm from '@/components/LoginForm'
import { useSession } from 'next-auth/react'

export default function Admin() {
  const { data: session } = useSession()

  return (
    <>
      {session ? (
        <>
          <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <meta
              name="viewport"
              content="width=device-width, initial-scale=1"
            />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <main>
            <h1>Сторінка адміну</h1>
            <LoginForm />
          </main>
        </>
      ) : (
        <LoginForm />
      )}
    </>
  )
}
