import Head from "next/head";
import type { NextPage } from "next";
import { useSession, signOut } from "next-auth/react";

const Admin: NextPage = () => {
  const { data: session } = useSession();

  const handleSignOut = async () => {
    await signOut({ callbackUrl: "/login" });
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Сторінка адміну</h1>
        <>
          Signed in as {session?.user?.name} <br />
          <button onClick={handleSignOut}>Sign out</button>
        </>
      </main>
    </>
  );
};

export default Admin;
